default_settings:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      beta: 5.0e-3
      buffer_size: 20480
      epsilon: 0.2
      num_epoch: 10000
      lambd: 0.90
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      vis_encode_type: simple
      num_layers: 2
      memory:
        sequence_length: 64
        memory_size: 128
      use_recurrent: false
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

behaviors:
  rl_deep_race:
    network_settings:
      normalize: true
      num_layers: 3
      hidden_units: 512
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
    time_horizon: 1000
    max_steps: 2e6
    summary_freq: 30000
    keep_checkpoints: 5
